CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'decision_vault') THEN
        CREATE SCHEMA decision_vault;
    END IF;
END $EF$;

CREATE TABLE decision_vault.categories (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(60) NOT NULL,
    "Kind" character varying(20) NOT NULL,
    "Description" character varying(300),
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_categories" PRIMARY KEY ("Id")
);

CREATE TABLE decision_vault.users (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FullName" character varying(100) NOT NULL,
    "Email" character varying(255) NOT NULL,
    "PasswordHash" character varying(100) NOT NULL,
    "Role" character varying(20) NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_users" PRIMARY KEY ("Id")
);

CREATE TABLE decision_vault.decision_events (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "DecisionId" integer NOT NULL,
    "EventType" character varying(40) NOT NULL,
    "Description" character varying(300) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_decision_events" PRIMARY KEY ("Id")
);

CREATE TABLE decision_vault.decision_options (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "DecisionId" integer NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Description" character varying(500),
    "Advantages" character varying(500),
    "Disadvantages" character varying(500),
    "Score" integer,
    "Weight" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_decision_options" PRIMARY KEY ("Id")
);

CREATE TABLE decision_vault.decisions (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "CategoryId" integer NOT NULL,
    "Title" character varying(200) NOT NULL,
    "Description" character varying(2000),
    "Status" character varying(20) NOT NULL,
    "DecisionDate" timestamp with time zone,
    "ReviewDate" timestamp with time zone,
    confidence_score integer,
    "ExpectedSuccessScore" integer,
    "ExpectedOutcome" character varying(1000),
    "SelectedOptionId" integer,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_decisions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_decisions_categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES decision_vault.categories ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_decisions_decision_options_SelectedOptionId" FOREIGN KEY ("SelectedOptionId") REFERENCES decision_vault.decision_options ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_decisions_users_UserId" FOREIGN KEY ("UserId") REFERENCES decision_vault.users ("Id") ON DELETE CASCADE
);

CREATE TABLE decision_vault.decision_reasons (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "DecisionId" integer NOT NULL,
    "Type" character varying(10) NOT NULL,
    "Category" character varying(60) NOT NULL,
    "Text" character varying(500) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_decision_reasons" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_decision_reasons_decisions_DecisionId" FOREIGN KEY ("DecisionId") REFERENCES decision_vault.decisions ("Id") ON DELETE CASCADE
);

CREATE TABLE decision_vault.decision_reviews (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "DecisionId" integer NOT NULL,
    "ActualOutcome" character varying(1000) NOT NULL,
    outcome_rating integer NOT NULL,
    "WhatWentWell" character varying(500),
    "WhatWentWrong" character varying(500),
    "LessonsLearned" character varying(500),
    "WouldChooseAgain" boolean NOT NULL,
    "IsSuccessful" boolean NOT NULL,
    "ReviewedAt" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_decision_reviews" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_decision_reviews_decisions_DecisionId" FOREIGN KEY ("DecisionId") REFERENCES decision_vault.decisions ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_categories_Name" ON decision_vault.categories ("Name");

CREATE INDEX "IX_decision_events_DecisionId_CreatedAt" ON decision_vault.decision_events ("DecisionId", "CreatedAt");

CREATE UNIQUE INDEX "IX_decision_options_DecisionId_Name" ON decision_vault.decision_options ("DecisionId", "Name");

CREATE INDEX "IX_decision_reasons_DecisionId" ON decision_vault.decision_reasons ("DecisionId");

CREATE UNIQUE INDEX "IX_decision_reviews_DecisionId" ON decision_vault.decision_reviews ("DecisionId");

CREATE INDEX "IX_decisions_CategoryId" ON decision_vault.decisions ("CategoryId");

CREATE INDEX "IX_decisions_SelectedOptionId" ON decision_vault.decisions ("SelectedOptionId");

CREATE INDEX "IX_decisions_UserId_CategoryId" ON decision_vault.decisions ("UserId", "CategoryId");

CREATE INDEX "IX_decisions_UserId_ReviewDate" ON decision_vault.decisions ("UserId", "ReviewDate");

CREATE INDEX "IX_decisions_UserId_Status_CreatedAt" ON decision_vault.decisions ("UserId", "Status", "CreatedAt");

CREATE UNIQUE INDEX "IX_users_Email" ON decision_vault.users ("Email");

ALTER TABLE decision_vault.decision_events ADD CONSTRAINT "FK_decision_events_decisions_DecisionId" FOREIGN KEY ("DecisionId") REFERENCES decision_vault.decisions ("Id") ON DELETE CASCADE;

ALTER TABLE decision_vault.decision_options ADD CONSTRAINT "FK_decision_options_decisions_DecisionId" FOREIGN KEY ("DecisionId") REFERENCES decision_vault.decisions ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260915072944_InitialCreate', '9.0.10');

COMMIT;

